[tool.nitpick]
style = [
  "github://MrP01/lint-me-now/nitpick-base-style.toml",
  "github://MrP01/lint-me-now/nitpick-c-cpp-style.toml",
  "github://MrP01/lint-me-now/nitpick-javascript-style.toml"
]
